server:
  port: 8080
spring:
  application:
    name: teste
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=teste;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Entrei241*
  # h2:
  #   console:
  #     enabled: true
  #     path: /banco
  jpa: 
    Hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
